// import '../example/updateProps'
// import '../example/propsOptions'
// import '../example/data'
// import '../example/methods'
// import '../example/computed'
// import '../example/lifeCycle'
// import '../example/mixins'
// import '../example/mixin'
import '../example/provide&inject'
